## Numpy 

In [ ]:
import numpy as np

In [ ]:
a1D = np.array([1, 2, 3, 4]) #'[] 1d array'
a2D = np.array([[1, 2], [3, 4]])#'[[]]'2d array'
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])#'[[[]]]'3d array

### Data type

bool: Boolean type storing True or False values.
    

int8, int16, int32, int64: Integer types with different sizes (in bits): 8-bit, 16-bit, 32-bit, and 64-bit, respectively.
        

uint8, uint16, uint32, uint64: Unsigned integer types with different sizes: 8-bit, 16-bit, 32-bit, and 64-bit, respectively.
        

float16, float32, float64: Floating-point types with different precision: 16-bit, 32-bit, and 64-bit, respectively.
        

complex64, complex128: Complex number types with different precision: 64-bit and 128-bit, respectively.
        

object: Python object type, allowing any Python object to be stored in the array.
    

string_: Fixed-length string type.
    

unicode_: Fixed-length Unicode type.

In [ ]:
a = np.array([2.45, 3.67, 4.56], dtype=np.int64)
print(a)

[2 3 4]


### Oparation On 2d array

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3] ) #row 0  # 1-dimensional array
print(arr1.shape)  # Output: (3,)
#arr1 has shape (3,) indicating a 1-dimensional array with 3 elements,

arr2 = np.array([
                [1, 2],# row0
                 [3, 4], #row 1
                 [5, 6] #row 2
                ])  # 2-dimensional array
print(arr2.shape)  # Output: (3, 2)
#arr2 has shape (3, 2) representing a 2-dimensional array with 3 rows and 2 columns, 

arr3 = np.array([[
    #layer 1
    [1, 2], #row 0
    [3, 4]], #row 1
    #layer 2
    [[5, 6], #row 0
     [7, 8]] #row 1
    ])  # 3-dimensional array
print(arr3.shape)
# Output: (2, 2, 2)
#arr3 has shape (2, 2, 2) indicating a 3-dimensional array with 2 layers, 2 rows, and 2 columns.

(3,)
(3, 2)
(2, 2, 2)


### Selecting Element of 2d array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
 # 0  1  2  3  4
# [1, 2, 3, 4, 5]
# Select a slice from index 1 to index 3 (exclusive)
print(arr[1:3])  # Output: [2 3]
#[1, [2, 3], 4, 5]
# Select elements from index 2 to the end
print(arr[2:])  # Output: [3 4 5]
# [1, 2, [3, 4, 5]]
# Select every other element
print(arr[::2])  # Output: [1 3 5]
# we select every second element starting from the first element. 
#[[1], 2, [3], 4, [5]]
# Select a slice from a multi-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[:, 1:3])  # Output: [[2 3] [5 6]]

[2 3]
[3 4 5]
[1 3 5]
[[2 3]
 [5 6]]


In [ ]:

arr = np.array([0,1, 2, 3,4,5,6,7,8,9] )
print(arr[::3])  # Output: [0 3 6 9]
print(arr[1::3])  # Output: [1 4 7]
print(arr[1::])  # Output: [1 2 3 4 5 6 7 8 9]
#  0th element  1st element   2nd element  3rd element   4th element
               # 0th element  1st element   2nd element  3rd element   4th element
                             # 0th element  1st element   2nd element  3rd element   4th element
                                           # 0th element  1st element   2nd element  3rd element   4th element
                                                         # 0th element  1st element   2nd element  3rd element   4th element
# [[1],             2,               [3],          4,           [5]]

[0 3 6 9]
[1 4 7]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# Modifying elements
arr[1] = 20
print(arr)

[ 0 20  2  3  4  5  6  7  8  9]


### Reshape to 1d array

In [ ]:
import numpy as np

# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)


# Create a multi-dimensional array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flatten the array using ravel
flattened_arr = arr.ravel()

print(flattened_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


### Array Oparation of any dim

In [ ]:
# Array operations
print(arr.sum())      # Output: 156
print(arr.mean())     # Output: 9.75
print(arr.max())      # Output: 20
print(arr.argmax())   # Output: 17 (index of the maximum element)

21
3.5
6
5


### 3 dim array

In [ ]:
import numpy as np

# Create a 3D array
arr = np.array([[#layer 0
                     # COL2
                [1, 2, 3],
                 [4, 5, 6],#row 1
                 [7, 8, 9]],
                #Layer 1
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

# Accessing individual elements
print(arr[0, 1, 2])  # Output: 6 #[layer ,row, colloumn] ,[layer0,row1,col2]

# Slicing along each dimension
print(arr[:, :, 1])  #(acsess two layer ,acsess col1)
# Output:
# [[ 2  5  8]
#  [11 14 17]]

print(arr[1, :, :])
# Output:
# [[10 11 12] #(acsess 1st layer only)
#  [13 14 15]
#  [16 17 18]]


# Modifying elements
arr[1, 2, 1] = 20
print(arr)
# Output:
# [[[ 1  2  3]
#   [ 4  5  6]
#   [ 7  8  9]]
#
#  [[10 11 12]
#   [13 14 15]
#   [16 20 18]]]


6
[[ 2  5  8]
 [11 14 17]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 20 18]]]


### Matrix calculation 

In [ ]:
import numpy as np

# Create matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using @ operator
C= A @ B

# Matrix multiplication using np.dot()
D = np.dot(A, B)

# Element-wise addition
E = A + B

# Element-wise multiplication
F = A * B

# Transpose using np.transpose()
G = np.transpose(A)

cross_product = np.cross(A, B)

print(cross_product)

print(C)
print(D)


[-4 -4]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
print("gh")

### Date calcualation

In [41]:
import numpy as np

# Perform arithmetic operations
dt1 = np.datetime64('2021-07-01')
dt2 = dt1 + np.timedelta64(7, 'D')  # Add 7 days
dt3 = dt1 - np.timedelta64(1, 'W')  # Subtract 1 week

print(dt2)  # Output: 2021-07-08
print(dt3)  # Output: 2021-06-24

# Compare dates
dt4 = np.datetime64('2021-07-15')

print(dt1 < dt4)  # Output: True
print(dt2 == dt4)  # Output: False

# Extract components of the date
year = np.datetime64('2021-07-01', 'Y')
month = np.datetime64('2021-07-01', 'M')
day = np.datetime64('2021-07-01', 'D')

print(year)  # Output: 2021
print(month)  # Output: 2021-07
print(day)  # Output: 2021-07-01

2021-07-08
2021-06-24
True
False
2021
2021-07
2021-07-01


### Missing Value Imputation

In [42]:
import numpy as np

# Create an array with missing values
arr = np.array([1, 2, np.nan, 4, 5])

# Calculate the mean of non-missing values
mean = np.nanmean(arr)

# Replace missing values with the mean
arr[np.isnan(arr)] = mean

print(arr)


[1. 2. 3. 4. 5.]


In [48]:
import numpy as np

# Create an array with missing values
arr = np.array([1, np.nan, 3, np.nan, 5])

# Forward fill missing values
arr_filled = np.nan_to_num(arr, nan=-1, copy=True)
np.maximum.accumulate(arr_filled, out=arr_filled)

print(arr_filled)


[1. 1. 3. 3. 5.]


### File creation and load

In [49]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Save the array to a file
np.save('array_file.npy', arr)

# Load the array from the file
loaded_arr = np.load('array_file.npy')

print(loaded_arr)

[1 2 3 4 5]
